name: Tox Python Version
description: >-
  Parses tox environment names and outputs the setup-python version to install
inputs:
  tox-env:
    descrition: Tox environment to run
    required: true
outputs:
  python-version:
    description: The appropriate Python version to pass to actions/setup-python
runs:
  using: 'node12'
  main: 'src/main.js'
