name: Test running with all the factors

"on":
  push:
  pull_request:

jobs:
  test:
    needs:
      - collect
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        env:
          - tox-env: py3
            expected: '3.x'
          - tox-env: py38
            expected: '3.8'
          - tox-env: lint-py38-foo
            expected: '3.8'
          - tox-env: py310-unit
            expected: '3.10'
          - tox-env: integration-py34
            expected: '3.4'
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          tox-env: ${{ matrix.env.tox-env }}
        id: tox
      - run: |
          assert '${{ matrix.env.expected }}' == '${{ steps.tox.outputs.python-version }}'
        shell: python
